name: cron test

on:
  # 当对分支main进行push操作的时候，这个工作流就被触发了
  push:
    branches: [ main ]
  schedule:
      # Runs everyday at 8:00 AM
      - cron: "0 8 * * *"     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
            echo abcd
